
name: Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        id: tests
        run: npm test
        continue-on-error: true
        env:
          NODE_ENV: test
          NODE_OPTIONS: --experimental-vm-modules
          DATABASE_URL: postgresql://test:test@localhost:5432/test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      - name: Generate test summary
        if: always()
        run: |
          if [ -f coverage/clover.xml ]; then
            echo "### Test Coverage Summary" >> $GITHUB_STEP_SUMMARY
            echo "Coverage report available as an artifact." >> $GITHUB_STEP_SUMMARY
          else
            echo "### No coverage report found." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Report test failures
        if: steps.tests.outcome == 'failure'
        run: |
          echo "::error title=Tests Failed::One or more tests failed. Check the logs for details."
          exit 1
